language: java
deploy:
  provider: heroku
  api_key:
    secure: H7tg2gY643rZrztNBfrC+vn0fO79PlwyxtQVCuk/NpG4/B0AHgmyjQgZhtLkaHYcKz6FJes1Y4E/iI2jBKp6zYfl1bMe07uUMpkEinU6tO4GR3cW4rjWwCStyaqAbzDvg0EowBNu1sgIdayCGi1+Hvpw2oyoF+MD9OHJIeIZZAvXDECbl0ncB2xsnBme2DAugicDDZJQ3cjgaNz69SNSqWopAA0i9IFYrHeSvRgsrspZb5I3vwOBX1pAGqQ6OqTH+yhswMq+0k3+HK18jNOmgXG4Vd3UdSmnNPrDRaxAi1doUGfEb07ONhENyVoqo7cxJgRjvAUUxoMEE4zLHmGY3Dm279+xdgnMzD44Br8Xsa9rl3ZOZFSWTVnTGLKXQpWMC5f6X9byU4T7/TwEfNaBtnVaa4pEZJxt2qpxAKNlMjhcGqFd30J+vFo/SAMHB/07nYctuI/zEAxHJj3fsiUW9IPsRe9aDSCr9nPoCekzNCK+kicYKmfH/5KrBHgee8Fx3f9xGr0avK0QkzkF05/I1M2ovVnP56NI7W5osDQ0WOwxpjiJj1dt6ZLwJ2VFLa23UL9noW2JTkkUV8iWRp6eYCrlv8hRcX6qc1m2ViSrS8RZub07d3/4NE6gRF6QW2GV8CqYLS/XfqFgXtY28zS7bZiN+lGM3gEkhVo+uQP55PY=
  app: jl-nielsen-assessment
