language: java
deploy:
  provider: heroku
  api_key:
    secure: fgQrWyk3arjQgVHwQ+DZe0RdaLJJQ8YpWu6Exq8FMGbzYVdIDCh5lphb67fHiyjmSbTYx4VIyV3rLKp29rqF1+Y4+Lm57LmLchZoMKPDTbDAYlpLGC0E9i+uuBbfR51SvcYpB+1p51JWSa5895fhIy0TvDRaBb4H/mJfRzCySOTOjZeOEZaNatBGw/RbW7kja3AUGghQ4RD8wl+w4i6TsBOb1dDr6huuyzSZW/JVvGeWuTFMdZBFoAjtTLITndmb+wcNB0QuOSomyehopdWD/dbCwQQjTu4mVcgqt4srbmK8ekJGwkxAM5M3ZsCeVaR9V+DZi6YeFy3X58k8g+g1bu8N0iYBmwimDOO6ojC2LYVF9w0re2Z7piVYaGHPsliNBFFsiYGW1uRs/k2xugw3vX6Ui9LyiqOCqWZ5zvn3qAnT/gf8E2pHgLOuymfqXTFK8FkxUylzXBeWV+bANV4Fym2FaUDF0wlN5qHkYiygqK1Pph0WD70fzfqPRPS1rRxIjLfpNssdB82lN5HN92NK8Bhq41ZtdIHK1jByzVtUYab2I3SzzVZac4/KpW7paM2FNxGDCtjWnUoO63KfM9uePRFiXkFZQpncL/bOoUwbagAsz0iQK3JBicTIS5573FC+Od9hMEu2vXHAsSdQ6ofeg+bwk9/iA7El4i+VHtOFi1k=
  app: jl-nielsen-assessment
