language: java
deploy:
  provider: heroku
  api_key:
    secure: J0ami8hgTy5iUL+XweZZBoBpqws2v22bPEBf7o9nnixus3jw0OCekyNW9P7BtsM+WO/4lbiGQn1eXECumeSkupiI8f01ivNtCmyM8NBBijT38LLebhe4CiINy3ln4J9kDgkJJR4QGcpCF+IL4o44KguANvYxAqQR7h0Yf7jydS80KYmVoUdQ3RVNI5aRCTlxBjP1vQgkRcUUV3e5t+clf2RrfPFI1m1HH5XUe7mt9l/0nalVIr+XVz23opjXnrvrZhtiq1QWbH+7gDhevcHWlRUlN3qAq0pzjRuHJ5t8G0qJPyY9s4dwx8XeY7Db6CaYrGYGrY7uQZx1gJ/lNT5Xx5Cr/fPht4K3oQUTBoNV27MRdszTEHBkQEi2ZfNDXoSijAUolKDaKh0mAKJ3OGB1ScN8BT8z49e3n0IvGtk82jqH2kufrZxN7H9Q1h3pTxHGASigPqVbueH9LLTFhyeCMolsAM9kA9jp649p2ySIxttC3UXlsqG0MR78skllO7sLxmaT6OmQR4hvaiaAQDiHxCxVSijA5T4x/KjqK0VQjaCLcYX5TncjL2/iJ+sZRfi9gesh6PUXr9UIlyClSgFis6jOEEDUlfVTxB4kGXcMeeC05rJOzttZd7+SiE2WcDTXFhmmyIBeUybsbqJ/Hx77anRHGxntS2iY1thgcBWEDmM=
  app: jl-nielsen-assessment
